name: Mengxin Ji
url: https://mengxinji.github.io/
description: PhD student in Resource Economics, UC Davis

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
